apiVersion: v1
kind: Service
metadata:
  name: sorting-visualizer-service
spec:
  type: NodePort
  selector:
    app: sorting-visualizer-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001